import Head from "next/head";
import { useDispatch, useSelector } from "react-redux";
import styles from "../styles/Home.module.css";
import { increment, decrement } from "../store/reducers/counter";
import { useEffect } from "react";
import { useRouter } from "next/router";
import axios from "axios";
import { getToken } from "../utils/hooks/common/cusAxios";

export default function Home() {
  const dispatch = useDispatch();
  const key = useSelector((state) => state.user.auth);
  const realtimeData = useSelector((state) => state.coin.realtimeData.data);
  const markets = useSelector((state) => state.coin.market.data);
  const router = useRouter();

  useEffect(() => {
    //router.push("/trading");

    (async () => {
      const account = await axios.get("/api/v1/accounts", {
        headers: {
          Authorization: getToken(key),
          Accept: `application/json`,
        },
      });

      const okMarkets = [...realtimeData]
        .sort((a, b) => b.acc_trade_price_24h - a.acc_trade_price_24h)
        .slice(0, 20)
        .map((x) => x.code);

      const acc = account.data
        .map((x) => {
          if (x.currency != "KRW") return "KRW-" + x.currency;
        })
        .filter((x) => x !== undefined);

      const result = [...new Set([...acc, ...okMarkets])];

      console.log(result);
    })();
  }, []);

  const count = useSelector((state) => state.counter.value);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Counter</h1>
      <h2>{count}</h2>
      <button onClick={() => dispatch(increment())}>+1</button>
      <button onClick={() => dispatch(decrement())}>-1</button>
    </div>
  );
}
